INSERT INTO "User" (username, user_password, email, biography, user_status, last_login, created_at, is_admin)
VALUES
    ('up202205295', md5('up202205295'), 'up202205295@up.pt', 'Biography of Diogo', 'Active', NOW(), NOW(), TRUE),
    ('up202206205', md5('up202206205'), 'up202206205@up.pt', 'Biography of Gonçalo', 'Active', NOW(), NOW(), TRUE),
    ('up202208296', md5('up202208296'), 'up202208296@up.pt', 'Biography of Lucas', 'Inactive', NOW() - INTERVAL '30 days', NOW() - INTERVAL '60 days', TRUE),
    ('up202208011', md5('up202208011'), 'up202208011@up.pt', 'Biography of Rui', 'Active', NOW(), NOW(), TRUE),
    ('up202208297', md5('up202208297'), 'up202208297@up.pt', 'Biography of User 297', 'Active', NOW(), NOW(), FALSE),
    ('up202208298', md5('up202208298'), 'up202208298@up.pt', 'Biography of User 298', 'Inactive', NOW() - INTERVAL '10 days', NOW() - INTERVAL '20 days', FALSE),
    ('up202208299', md5('up202208299'), 'up202208299@up.pt', 'Biography of User 299', 'Active', NOW(), NOW(), FALSE),
    ('up202208300', md5('up202208300'), 'up202208300@up.pt', 'Biography of User 300', 'Active', NOW(), NOW(), FALSE),
    ('up202208301', md5('up202208301'), 'up202208301@up.pt', 'Biography of User 301', 'Active', NOW(), NOW(), FALSE),
    ('up202208302', md5('up202208302'), 'up202208302@up.pt', 'Biography of User 302', 'Inactive', NOW() - INTERVAL '5 days', NOW() - INTERVAL '15 days', FALSE),
    ('up202208303', md5('up202208303'), 'up202208303@up.pt', 'Biography of User 303', 'Active', NOW(), NOW(), FALSE),
    ('up202208304', md5('up202208304'), 'up202208304@up.pt', 'Biography of User 304', 'Active', NOW(), NOW(), FALSE),
    ('up202208305', md5('up202208305'), 'up202208305@up.pt', 'Biography of User 305', 'Active', NOW(), NOW(), FALSE),
    ('up202208306', md5('up202208306'), 'up202208306@up.pt', 'Biography of User 306', 'Active', NOW(), NOW(), FALSE),
    ('up202208392', md5('up202208392'), 'up202208392@up.pt', 'Biography of User 392', 'Inactive', NOW() - INTERVAL '20 days', NOW() - INTERVAL '30 days', FALSE),
    ('up202208393', md5('up202208393'), 'up202208393@up.pt', 'Biography of User 393', 'Active', NOW(), NOW(), FALSE),
    ('up202208394', md5('up202208394'), 'up202208394@up.pt', 'Biography of User 394', 'Active', NOW(), NOW(), FALSE),
    ('up202208395', md5('up202208395'), 'up202208395@up.pt', 'Biography of User 395', 'Active', NOW(), NOW(), FALSE),
    ('up202208396', md5('up202208396'), 'up202208396@up.pt', 'Biography of User 396', 'Active', NOW(), NOW(), FALSE),
    ('up202208397', md5('up202208397'), 'up202208397@up.pt', 'Biography of User 397', 'Active', NOW(), NOW(), FALSE),
    ('up202208398', md5('up202208398'), 'up202208398@up.pt', 'Biography of User 398', 'Active', NOW(), NOW(), FALSE),
    ('up202208399', md5('up202208399'), 'up202208399@up.pt', 'Biography of User 399', 'Active', NOW(), NOW(), FALSE),
    ('up202208400', md5('up202208400'), 'up202208400@up.pt', 'Biography of User 400', 'Inactive', NOW() - INTERVAL '10 days', NOW() - INTERVAL '20 days', FALSE),
    ('up202208401', md5('up202208401'), 'up202208401@up.pt', 'Biography of User 401', 'Active', NOW(), NOW(), FALSE),
    ('up202208402', md5('up202208402'), 'up202208402@up.pt', 'Biography of User 402', 'Active', NOW(), NOW(), FALSE),
    ('up202208403', md5('up202208403'), 'up202208403@up.pt', 'Biography of User 403', 'Inactive', NOW() - INTERVAL '15 days', NOW() - INTERVAL '25 days', FALSE),
    ('up202208404', md5('up202208404'), 'up202208404@up.pt', 'Biography of User 404', 'Active', NOW(), NOW(), FALSE),
    ('up202208405', md5('up202208405'), 'up202208405@up.pt', 'Biography of User 405', 'Active', NOW(), NOW(), FALSE),
    ('up202208406', md5('up202208406'), 'up202208406@up.pt', 'Biography of User 406', 'Active', NOW(), NOW(), FALSE),
    ('up202208407', md5('up202208407'), 'up202208407@up.pt', 'Biography of User 407', 'Active', NOW(), NOW(), FALSE),
    ('up202208408', md5('up202208408'), 'up202208408@up.pt', 'Biography of User 408', 'Inactive', NOW() - INTERVAL '7 days', NOW() - INTERVAL '14 days', FALSE),
    ('up202208409', md5('up202208409'), 'up202208409@up.pt', 'Biography of User 409', 'Active', NOW(), NOW(), FALSE),
    ('up202208410', md5('up202208410'), 'up202208410@up.pt', 'Biography of User 410', 'Active', NOW(), NOW(), FALSE),
    ('up202208411', md5('up202208411'), 'up202208411@up.pt', 'Biography of User 411', 'Active', NOW(), NOW(), FALSE),
    ('up202208412', md5('up202208412'), 'up202208412@up.pt', 'Biography of User 412', 'Inactive', NOW() - INTERVAL '12 days', NOW() - INTERVAL '22 days', FALSE),
    ('up202208413', md5('up202208413'), 'up202208413@up.pt', 'Biography of User 413', 'Active', NOW(), NOW(), FALSE),
    ('up202208414', md5('up202208414'), 'up202208414@up.pt', 'Biography of User 414', 'Active', NOW(), NOW(), FALSE),
    ('up202208415', md5('up202208415'), 'up202208415@up.pt', 'Biography of User 415', 'Active', NOW(), NOW(), FALSE),
    ('up202208416', md5('up202208416'), 'up202208416@up.pt', 'Biography of User 416', 'Active', NOW(), NOW(), FALSE),
    ('up202208417', md5('up202208417'), 'up202208417@up.pt', 'Biography of User 417', 'Active', NOW(), NOW(), FALSE),
    ('up202208418', md5('up202208418'), 'up202208418@up.pt', 'Biography of User 418', 'Active', NOW(), NOW(), FALSE),
    ('up202208419', md5('up202208419'), 'up202208419@up.pt', 'Biography of User 419', 'Inactive', NOW() - INTERVAL '10 days', NOW() - INTERVAL '20 days', FALSE),
    ('up202208420', md5('up202208420'), 'up202208420@up.pt', 'Biography of User 420', 'Active', NOW(), NOW(), FALSE),
    ('up202208421', md5('up202208421'), 'up202208421@up.pt', 'Biography of User 421', 'Active', NOW(), NOW(), FALSE),
    ('up202208422', md5('up202208422'), 'up202208422@up.pt', 'Biography of User 422', 'Inactive', NOW() - INTERVAL '5 days', NOW() - INTERVAL '15 days', FALSE),
    ('up202208423', md5('up202208423'), 'up202208423@up.pt', 'Biography of User 423', 'Active', NOW(), NOW(), FALSE),
    ('up202208424', md5('up202208424'), 'up202208424@up.pt', 'Biography of User 424', 'Active', NOW(), NOW(), FALSE),
    ('up202208425', md5('up202208425'), 'up202208425@up.pt', 'Biography of User 425', 'Active', NOW(), NOW(), FALSE),
    ('up202208426', md5('up202208426'), 'up202208426@up.pt', 'Biography of User 426', 'Inactive', NOW() - INTERVAL '3 days', NOW() - INTERVAL '12 days', FALSE),
    ('up202208427', md5('up202208427'), 'up202208427@up.pt', 'Biography of User 427', 'Active', NOW(), NOW(), FALSE),
    ('up202208428', md5('up202208428'), 'up202208428@up.pt', 'Biography of User 428', 'Active', NOW(), NOW(), FALSE),
    ('up202208429', md5('up202208429'), 'up202208429@up.pt', 'Biography of User 429', 'Active', NOW(), NOW(), FALSE),
    ('up202208430', md5('up202208430'), 'up202208430@up.pt', 'Biography of User 430', 'Active', NOW(), NOW(), FALSE),
    ('up202208431', md5('up202208431'), 'up202208431@up.pt', 'Biography of User 431', 'Inactive', NOW() - INTERVAL '14 days', NOW() - INTERVAL '25 days', FALSE),
    ('up202208432', md5('up202208432'), 'up202208432@up.pt', 'Biography of User 432', 'Active', NOW(), NOW(), FALSE),
    ('up202208433', md5('up202208433'), 'up202208433@up.pt', 'Biography of User 433', 'Active', NOW(), NOW(), FALSE),
    ('up202208434', md5('up202208434'), 'up202208434@up.pt', 'Biography of User 434', 'Active', NOW(), NOW(), FALSE),
    ('up202208435', md5('up202208435'), 'up202208435@up.pt', 'Biography of User 435', 'Inactive', NOW() - INTERVAL '7 days', NOW() - INTERVAL '17 days', FALSE),
    ('up202208436', md5('up202208436'), 'up202208436@up.pt', 'Biography of User 436', 'Active', NOW(), NOW(), FALSE);

INSERT INTO TaskStatus (task_status_name)
VALUES
    ('Not Started'),       
    ('In Progress'),       
    ('Completed'),         
    ('On Hold'),           
    ('Cancelled'),         
    ('Waiting for Review'),
    ('Deferred'),          
    ('Needs Attention'),   
    ('Blocked'),           
    ('Ready for Deployment'); 


INSERT INTO Project (project_name, project_description, created_at, project_status, creator_id)
VALUES
    ('Project Management System', 'A system to manage various project tasks and members', NOW(), 'Active', 1),
    ('CRM Platform', 'A customer relationship management platform', NOW() - INTERVAL '10 days', 'Active', 2),
    ('Inventory Tracking', 'A solution for tracking stock and inventory levels', NOW() - INTERVAL '20 days', 'Active', 3),
    ('E-commerce Platform', 'A comprehensive platform for online shopping', NOW(), 'Completed', 4),
    ('Social Media Analytics', 'A tool to analyze social media performance', NOW() - INTERVAL '30 days', 'Archived', 5),
    ('Task Automation Tool', 'A platform for automating repetitive tasks', NOW(), 'Active', 6),
    ('Marketing Campaign Manager', 'A solution for managing marketing campaigns', NOW() - INTERVAL '5 days', 'Active', 7),
    ('Event Management System', 'A platform for managing events and attendees', NOW(), 'Active', 8),
    ('Learning Management System', 'A platform for educational institutions to manage courses', NOW() - INTERVAL '15 days', 'Archived', 9),
    ('Budgeting Tool', 'A tool to manage budgets for small businesses', NOW(), 'Completed', 10),
    ('Employee Performance Tracker', 'A solution for tracking employee performance', NOW() - INTERVAL '25 days', 'Active', 11),
    ('Time Management App', 'A mobile app for managing time efficiently', NOW(), 'Active', 12),
    ('File Sharing Platform', 'A solution for secure file sharing', NOW() - INTERVAL '10 days', 'Archived', 13),
    ('HR Management System', 'A platform to manage human resources and payroll', NOW(), 'Active', 14),
    ('Content Management System', 'A tool for managing digital content', NOW() - INTERVAL '20 days', 'Active', 15),
    ('Online Banking System', 'A platform for managing personal finances online', NOW(), 'Active', 16),
    ('Fitness Tracker', 'An app for tracking fitness goals and activities', NOW() - INTERVAL '30 days', 'Completed', 17),
    ('Travel Booking System', 'A platform to manage travel bookings and itineraries', NOW(), 'Active', 18),
    ('AI Chatbot', 'A chatbot for handling customer inquiries', NOW() - INTERVAL '5 days', 'Active', 19),
    ('Cloud Storage Solution', 'A secure solution for cloud data storage', NOW(), 'Archived', 20),
    ('Online Survey Tool', 'A tool to create and distribute online surveys', NOW(), 'Active', 21),
    ('Expense Tracker', 'An application to track personal expenses and income', NOW() - INTERVAL '15 days', 'Active', 22),
    ('Health Monitoring System', 'A system to monitor patients’ health status remotely', NOW(), 'Completed', 23),
    ('Online Gaming Platform', 'A platform for hosting and playing online games', NOW() - INTERVAL '25 days', 'Active', 24),
    ('Weather Forecasting App', 'An app for real-time weather updates', NOW() - INTERVAL '10 days', 'Archived', 25),
    ('Project Collaboration Tool', 'A platform for real-time collaboration on projects', NOW(), 'Active', 26),
    ('E-learning Platform', 'An educational platform for online learning', NOW() - INTERVAL '5 days', 'Active', 27),
    ('Bug Tracking System', 'A tool for tracking bugs in software development', NOW(), 'Active', 28),
    ('Online Forum', 'A forum for discussions and community building', NOW() - INTERVAL '30 days', 'Archived', 29),
    ('Remote Work Platform', 'A platform for managing remote teams', NOW(), 'Completed', 30),
    ('Virtual Meeting Tool', 'A tool for hosting virtual meetings and webinars', NOW() - INTERVAL '20 days', 'Active', 31),
    ('Supply Chain Management', 'A platform to manage supply chain logistics', NOW(), 'Active', 32),
    ('Customer Support System', 'A tool for managing customer support tickets', NOW() - INTERVAL '10 days', 'Archived', 33),
    ('Personal Finance App', 'A mobile app for managing personal finances', NOW(), 'Active', 34),
    ('Social Networking Platform', 'A platform for connecting with friends and sharing updates', NOW() - INTERVAL '15 days', 'Active', 35),
    ('Online Voting System', 'A secure system for online voting and elections', NOW(), 'Active', 36),
    ('Mobile Payment Solution', 'A platform for mobile payments and transactions', NOW() - INTERVAL '25 days', 'Completed', 37),
    ('Task Scheduler', 'A tool to manage and schedule tasks efficiently', NOW(), 'Active', 38),
    ('Digital Library System', 'A platform for managing digital books and resources', NOW() - INTERVAL '30 days', 'Archived', 39),
    ('Event Ticketing System', 'A system for buying and selling event tickets online', NOW(), 'Active', 40),
    ('Fitness Coaching App', 'An app for tracking fitness progress and getting personalized workout plans', NOW(), 'Active', 41),
    ('Home Automation System', 'A system to control home appliances remotely', NOW() - INTERVAL '10 days', 'Active', 42),
    ('Job Board Platform', 'An online platform for job listings and applications', NOW(), 'Completed', 43),
    ('Crowdfunding Platform', 'A system for raising funds for various causes or projects', NOW() - INTERVAL '20 days', 'Active', 44),
    ('Virtual Reality Gaming', 'A platform for virtual reality gaming experiences', NOW(), 'Active', 45),
    ('AI-powered Chatbot', 'A chatbot system powered by artificial intelligence', NOW() - INTERVAL '5 days', 'Archived', 46),
    ('Blockchain Wallet', 'A digital wallet for managing cryptocurrency transactions', NOW(), 'Active', 47),
    ('Online Marketplace', 'An e-commerce platform for buying and selling products', NOW() - INTERVAL '15 days', 'Active', 48),
    ('Video Conferencing Tool', 'A tool for virtual meetings and remote collaboration', NOW(), 'Completed', 49),
    ('Food Delivery App', 'An app to order food from local restaurants and have it delivered', NOW() - INTERVAL '30 days', 'Active', 50),
    ('Real Estate Listing Platform', 'A platform for listing and browsing properties for sale or rent', NOW(), 'Active', 51),
    ('Digital Advertising Tool', 'A tool for managing online advertising campaigns', NOW() - INTERVAL '25 days', 'Archived', 52),
    ('Travel Planning App', 'An app for planning trips and booking hotels or flights', NOW(), 'Active', 53),
    ('Project Budgeting Tool', 'A tool for managing project budgets and expenses', NOW() - INTERVAL '10 days', 'Active', 54),
    ('IoT Device Manager', 'A platform for managing and controlling IoT devices remotely', NOW(), 'Completed', 55),
    ('Language Learning App', 'An app to learn new languages through interactive lessons', NOW() - INTERVAL '15 days', 'Active', 56),
    ('Music Streaming Service', 'A platform for streaming music from various artists', NOW(), 'Active', 57),
    ('Remote Healthcare System', 'A system for remote patient monitoring and consultations', NOW() - INTERVAL '5 days', 'Archived', 58),
    ('Task Management Tool', 'A tool to assign and track project tasks', NOW(), 'Active', 59);

INSERT INTO Invitation (invitation_message, sender_id, receiver_id, project_id)
VALUES
    ('You are invited to join the Project Management System', 1, 5, 1),
    ('You are invited to join the CRM Platform project', 2, 6, 2),
    ('You are invited to join the Inventory Tracking project', 3, 7, 3),
    ('Please join the E-commerce Platform project', 4, 8, 4),
    ('Invitation to join the Social Media Analytics project', 5, 9, 5),
    ('Invitation to collaborate on the Task Automation Tool', 6, 10, 6),
    ('Join the Marketing Campaign Manager project', 7, 11, 7),
    ('Please join the Event Management System project', 8, 12, 8),
    ('Invitation to collaborate on the Learning Management System', 9, 13, 9),
    ('Join the Budgeting Tool project', 10, 14, 10),
    ('You are invited to join the Employee Performance Tracker', 11, 15, 11),
    ('Join the Time Management App project', 12, 16, 12),
    ('Invitation to collaborate on the File Sharing Platform', 13, 17, 13),
    ('Please join the HR Management System project', 14, 18, 14),
    ('Invitation to join the Content Management System project', 15, 19, 15),
    ('Join the Online Banking System project', 16, 20, 16),
    ('Invitation to collaborate on the Fitness Tracker project', 17, 21, 17),
    ('You are invited to join the Travel Booking System', 18, 22, 18),
    ('Join the AI Chatbot project', 19, 23, 19),
    ('Please join the Cloud Storage Solution project', 20, 24, 20),
    ('You are invited to join the Online Survey Tool project', 21, 25, 21),
    ('Join the Expense Tracker project as a collaborator', 22, 26, 22),
    ('Invitation to collaborate on the Health Monitoring System', 23, 27, 23),
    ('Please join the Online Gaming Platform project', 24, 28, 24),
    ('Join the Weather Forecasting App team', 25, 29, 25),
    ('You are invited to the Project Collaboration Tool', 26, 30, 26),
    ('Invitation to join the E-learning Platform project', 27, 31, 27),
    ('Join the Bug Tracking System team', 28, 32, 28),
    ('Please collaborate on the Online Forum project', 29, 33, 29),
    ('Invitation to join the Remote Work Platform project', 30, 34, 30),
    ('You are invited to the Virtual Meeting Tool project', 31, 35, 31),
    ('Join the Supply Chain Management project as a member', 32, 36, 32),
    ('Invitation to collaborate on the Customer Support System project', 33, 37, 33),
    ('Please join the Personal Finance App project', 34, 38, 34),
    ('Invitation to work on the Social Networking Platform', 35, 39, 35),
    ('Join the Online Voting System project', 36, 40, 36),
    ('Invitation to collaborate on the Mobile Payment Solution', 37, 41, 37),
    ('Please join the Task Scheduler project', 38, 42, 38),
    ('Join the Digital Library System project as a contributor', 39, 43, 39),
    ('You are invited to work on the Event Ticketing System project', 40, 44, 40),
    ('Join the Fitness Coaching App project as a collaborator', 41, 45, 41),
    ('You are invited to the Home Automation System project', 42, 46, 42),
    ('Invitation to join the Job Board Platform project', 43, 47, 43),
    ('Please collaborate on the Crowdfunding Platform', 44, 48, 44),
    ('Join the Virtual Reality Gaming team', 45, 49, 45),
    ('Invitation to work on the AI-powered Chatbot', 46, 50, 46),
    ('You are invited to collaborate on the Blockchain Wallet project', 47, 51, 47),
    ('Join the Online Marketplace project', 48, 52, 48),
    ('Invitation to collaborate on the Video Conferencing Tool', 49, 53, 49),
    ('Please join the Food Delivery App project', 50, 54, 50),
    ('Join the Real Estate Listing Platform project as a team member', 51, 55, 51),
    ('Invitation to join the Digital Advertising Tool project', 52, 56, 52),
    ('Please collaborate on the Travel Planning App', 53, 57, 53),
    ('You are invited to the Project Budgeting Tool', 54, 58, 54),
    ('Join the IoT Device Manager project', 55, 59, 55);

INSERT INTO Task (task_title, task_description, created_at, deadline, task_status_id, task_priority, project_id, user_id)
VALUES
    ('Setup Database', 'Set up the initial database for the project.', NOW(), NOW() + INTERVAL '7 days', 1, 'High', 1, 1),
    ('Design UI Mockups', 'Create UI mockups for the frontend design.', NOW(), NOW() + INTERVAL '10 days', 1, 'Medium', 2, 2),
    ('Develop API Endpoints', 'Develop API endpoints for user management.', NOW(), NULL, 3, 'Low', 3, 3),
    ('Integrate Payment Gateway', 'Integrate payment gateway for e-commerce transactions.', NOW(), NOW() + INTERVAL '15 days', 3, 'High', 4, 4),
    ('Write Unit Tests', 'Write unit tests for backend functionality.', NOW(), NOW() + INTERVAL '20 days', 9, 'Medium', 5, 5),
    ('Setup CI/CD Pipeline', 'Implement continuous integration and delivery pipeline.', NOW(), NOW() + INTERVAL '8 days', 9, 'High', 6, 6),
    ('Create User Documentation', 'Write user-facing documentation for the platform.', NOW(), NULL, 8, 'Low', 7, 7),
    ('Design Event Pages', 'Design pages for event management.', NOW(), NOW() + INTERVAL '12 days', 8, 'Medium', 8, 8),
    ('Implement Course Management', 'Implement course management features.', NOW(), NOW() + INTERVAL '18 days', 7, 'High', 9, 9),
    ('Optimize Budgeting Tool', 'Optimize performance of the budgeting tool.', NOW(), NOW() + INTERVAL '22 days', 7, 'Medium', 10, 10),
    ('Develop Employee Tracker', 'Develop a tracker for employee performance.', NOW(), NULL, 6, 'Low', 11, 11),
    ('Test Time Management Features', 'Test the time management features.', NOW(), NOW() + INTERVAL '5 days', 6, 'High', 12, 12),
    ('Fix Bugs in File Sharing', 'Fix critical bugs in the file sharing platform.', NOW(), NOW() + INTERVAL '9 days', 4, 'Medium', 13, 13),
    ('Setup Payroll System', 'Setup the payroll system for HR management.', NOW(), NULL, 4, 'Low', 14, 14),
    ('Develop Content Editing Tool', 'Develop tools for editing digital content.', NOW(), NOW() + INTERVAL '13 days', 2, 'High', 15, 15),
    ('Implement Financial Tracking', 'Implement features for online banking system.', NOW(), NOW() + INTERVAL '17 days', 2, 'Medium', 16, 16),
    ('Develop Fitness App Features', 'Develop tracking features for fitness goals.', NOW(), NOW() + INTERVAL '21 days', 2, 'High', 17, 17),
    ('Test Travel Booking Flow', 'Test the booking flow for travel itineraries.', NOW(), NOW() + INTERVAL '6 days', 2, 'Medium', 18, 18),
    ('Enhance AI Chatbot', 'Enhance chatbot features for customer support.', NOW(), NULL, 2, 'Low', 19, 19),
    ('Secure Cloud Storage', 'Implement security features for cloud data.', NOW(), NOW() + INTERVAL '10 days', 1, 'High', 20, 20),
    ('Develop Survey Creation Tool', 'Develop features to allow users to create custom surveys.', NOW(), NOW() + INTERVAL '14 days', 1, 'Medium', 21, 21),
    ('Implement Expense Tracking', 'Add features to track expenses and incomes.', NOW(), NOW() + INTERVAL '10 days', 1, 'High', 22, 22),
    ('Monitor Patient Health', 'Implement real-time health monitoring for patients.', NOW(), NOW() + INTERVAL '20 days', 1, 'High', 23, 23),
    ('Develop Multiplayer Features', 'Add multiplayer functionality to the online gaming platform.', NOW(), NOW() + INTERVAL '25 days', 4, 'Low', 24, 24),
    ('Integrate Weather API', 'Integrate external API for fetching real-time weather data.', NOW(), NOW() + INTERVAL '18 days', 4, 'Medium', 25, 25),
    ('Real-Time Collaboration', 'Develop real-time collaboration tools for the project management system.', NOW(), NOW() + INTERVAL '12 days', 4, 'High', 26, 26),
    ('Build E-Learning Modules', 'Create and organize modules for the online learning platform.', NOW(), NOW() + INTERVAL '22 days', 5, 'Medium', 27, 27),
    ('Track Bug Reports', 'Implement a bug tracking feature for project management.', NOW(), NULL, 5, 'Low', 28, 28),
    ('Moderate Forum Discussions', 'Develop tools for moderators to manage forum discussions.', NOW(), NOW() + INTERVAL '5 days', 5, 'Medium', 29, 29),
    ('Setup Remote Work Tools', 'Implement tools for managing remote teams.', NOW(), NOW() + INTERVAL '8 days', 6, 'Low', 30, 30),
    ('Develop Video Conferencing Features', 'Create features to support video conferencing and webinars.', NOW(), NOW() + INTERVAL '9 days', 6, 'High', 31, 31),
    ('Automate Supply Chain Processes', 'Implement automation for supply chain logistics.', NOW(), NOW() + INTERVAL '15 days', 6, 'High', 32, 32),
    ('Improve Customer Support Chat', 'Enhance live chat features for customer support.', NOW(), NOW() + INTERVAL '11 days', 3, 'Medium', 33, 33),
    ('Add Personal Finance Calculator', 'Add a tool for users to calculate personal finances.', NOW(), NOW() + INTERVAL '7 days', 3, 'High', 34, 34),
    ('Design Social Networking Feed', 'Develop the user feed for the social networking platform.', NOW(), NULL, 3, 'Medium', 35, 35),
    ('Secure Voting Platform', 'Implement security features for online voting.', NOW(), NOW() + INTERVAL '10 days', 3, 'High', 36, 36),
    ('Develop Mobile Payment System', 'Develop a secure mobile payment system.', NOW(), NOW() + INTERVAL '16 days', 1, 'High', 37, 37),
    ('Optimize Task Scheduler', 'Optimize the performance of the task scheduling algorithm.', NOW(), NULL, 1, 'Medium', 38, 38),
    ('Create Digital Library Catalog', 'Develop the catalog feature for managing digital books.', NOW(), NOW() + INTERVAL '14 days', 1, 'Low', 39, 39),
    ('Setup Ticketing System', 'Set up a system for buying and selling event tickets.', NOW(), NOW() + INTERVAL '21 days', 1, 'High', 40, 40),
    ('Develop Fitness Progress Tracker', 'Create a feature to track users’ fitness progress.', NOW(), NOW() + INTERVAL '12 days', 2, 'Medium', 41, 41),
    ('Implement Home Automation Controls', 'Create user interfaces to control smart home devices.', NOW(), NOW() + INTERVAL '8 days', 2, 'High', 42, 42),
    ('Set Up Job Posting Features', 'Develop features for users to post and apply for jobs.', NOW(), NOW() + INTERVAL '14 days', 2, 'Medium', 43, 43),
    ('Design Crowdfunding Campaign Pages', 'Create templates for different types of crowdfunding campaigns.', NOW(), NOW() + INTERVAL '18 days', 2, 'Low', 44, 44),
    ('Build Virtual Reality Gaming Lobby', 'Develop the multiplayer lobby for virtual reality games.', NOW(), NOW() + INTERVAL '20 days', 2, 'High', 45, 45),
    ('Optimize AI Chatbot Responses', 'Improve the chatbot response time and accuracy.', NOW(), NOW() + INTERVAL '15 days', 4, 'Medium', 46, 46),
    ('Develop Cryptocurrency Wallet Security', 'Implement security measures for blockchain wallet.', NOW(), NOW() + INTERVAL '22 days', 4, 'High', 47, 47),
    ('Add Product Review Features', 'Create features for product reviews on the marketplace.', NOW(), NOW() + INTERVAL '16 days', 6, 'Medium', 48, 48),
    ('Integrate Video Streaming Tools', 'Develop the integration of video streaming services.', NOW(), NOW() + INTERVAL '13 days', 6, 'Medium', 49, 49),
    ('Optimize Food Delivery Routes', 'Develop algorithms for optimizing food delivery routes.', NOW(), NOW() + INTERVAL '19 days', 7, 'High', 50, 50),
    ('Create Property Listings', 'Develop features for real estate property listings.', NOW(), NOW() + INTERVAL '9 days', 7, 'Medium', 51, 51),
    ('Develop Digital Advertising Campaign Manager', 'Create tools for managing digital advertising campaigns.', NOW(), NOW() + INTERVAL '11 days', 8, 'High', 52, 52),
    ('Implement Travel Booking Payments', 'Integrate payment systems for travel bookings.', NOW(), NOW() + INTERVAL '5 days', 8, 'High', 53, 53),
    ('Optimize Project Budgeting Calculations', 'Improve the performance of budgeting calculations.', NOW(), NOW() + INTERVAL '14 days', 9, 'Medium', 54, 54),
    ('Secure IoT Device Communication', 'Develop security protocols for IoT devices.', NOW(), NOW() + INTERVAL '10 days', 9, 'High', 55, 55),
    ('Build Language Learning Quizzes', 'Create quizzes for language learners to practice.', NOW(), NOW() + INTERVAL '6 days', 3, 'Low', 56, 56),
    ('Design Music Playlist Features', 'Develop features for creating and managing music playlists.', NOW(), NOW() + INTERVAL '7 days', 3, 'Medium', 57, 57),
    ('Develop Remote Healthcare Monitoring', 'Create features for real-time patient monitoring.', NOW(), NOW() + INTERVAL '12 days', 5, 'High', 58, 58),
    ('Enhance Task Management Filters', 'Add advanced filters for task management views.', NOW(), NOW() + INTERVAL '9 days', 5, 'Low', 59, 59);

INSERT INTO AssignedTask (user_id, task_id)
VALUES
    (1, 1),   
    (2, 2),   
    (3, 3),   
    (4, 4),   
    (5, 5),   
    (6, 6),   
    (7, 7),   
    (8, 8),   
    (9, 9),   
    (10, 10), 
    (11, 11), 
    (12, 12), 
    (13, 13), 
    (14, 14), 
    (15, 15), 
    (16, 16), 
    (17, 17), 
    (18, 18), 
    (19, 19), 
    (20, 20),
    (21, 21),  
    (22, 22),  
    (23, 23),  
    (24, 24),  
    (25, 25),  
    (26, 26),  
    (27, 27),  
    (28, 28),  
    (29, 29),  
    (30, 30),  
    (31, 31),  
    (32, 32),  
    (33, 33),  
    (34, 34),  
    (35, 35),  
    (36, 36),  
    (37, 37),  
    (38, 38),  
    (39, 39),  
    (40, 40);  

INSERT INTO "Comment" (comment_content, created_at, task_id)
VALUES
    ('Initial setup instructions', NOW(), 1),
    ('Further clarification on setup', NOW(), 1),
    ('UI mockup feedback', NOW(), 2),
    ('Design review comments', NOW(), 2),
    ('API authentication discussion', NOW(), 3),
    ('API improvement suggestions', NOW(), 3),
    ('Payment gateway issue identified', NOW(), 4),
    ('Resolved payment gateway issue', NOW(), 4),
    ('Unit testing requires more scenarios', NOW(), 5),
    ('Unit testing feedback review', NOW(), 5),
    ('CI/CD pipeline feedback', NOW(), 6),
    ('Pipeline optimization suggestions', NOW(), 6),
    ('User documentation feedback', NOW(), 7),
    ('Documentation revisions required', NOW(), 7),
    ('Event page design comments', NOW(), 8),
    ('Suggestions for event page', NOW(), 8),
    ('Course management feedback', NOW(), 9),
    ('Course feature enhancement ideas', NOW(), 9),
    ('Budgeting tool optimizations', NOW(), 10),
    ('Performance review on budget tool', NOW(), 10),
    ('Employee tracker feedback', NOW(), 11),
    ('Discussion on employee performance features', NOW(), 11),
    ('Time management app feedback', NOW(), 12),
    ('Suggestions for time tracking improvement', NOW(), 12),
    ('File sharing platform issues', NOW(), 13),
    ('Resolved file sharing issues', NOW(), 13),
    ('HR system improvements', NOW(), 14),
    ('Payroll system setup feedback', NOW(), 14),
    ('Content management system feedback', NOW(), 15),
    ('Content editor enhancement ideas', NOW(), 15),
    ('Online banking tool feedback', NOW(), 16),
    ('Suggestions for financial tracking features', NOW(), 16),
    ('Fitness tracker update suggestions', NOW(), 17),
    ('Resolved issues with fitness tracking features', NOW(), 17),
    ('Travel booking system issues', NOW(), 18),
    ('Improvements to travel booking flow', NOW(), 18),
    ('Survey tool feedback', NOW(), 21),
    ('Discussion on custom survey creation', NOW(), 21),
    ('Expense tracker tool feedback', NOW(), 22),
    ('Resolved issues with expense tracking', NOW(), 22);

INSERT INTO CommentRelation (child_id, parent_id)
VALUES
    (2, 1),   
    (4, 3),   
    (6, 5),   
    (8, 7),   
    (10, 9),  
    (12, 11), 
    (14, 13), 
    (16, 15), 
    (18, 17), 
    (20, 19), 
    (22, 21),  
    (24, 23), 
    (26, 25), 
    (28, 27), 
    (30, 29), 
    (32, 31), 
    (34, 33), 
    (36, 35), 
    (38, 37), 
    (40, 39); 

INSERT INTO ProjectRole (user_id, project_id, user_role)
VALUES
    (1, 1, 'ProjectCoordinator'),
    (2, 2, 'ProjectCoordinator'), 
    (3, 3, 'ProjectCoordinator'), 
    (4, 4, 'ProjectCoordinator'), 
    (5, 5, 'ProjectCoordinator'), 
    (6, 6, 'ProjectCoordinator'),  
    (7, 7, 'ProjectCoordinator'),  
    (8, 8, 'ProjectCoordinator'),  
    (9, 9, 'ProjectCoordinator'),  
    (10, 10, 'ProjectCoordinator'),  
    (11, 11, 'ProjectMember'),  
    (12, 12, 'ProjectMember'),  
    (13, 13, 'ProjectMember'),  
    (14, 14, 'ProjectMember'),  
    (15, 15, 'ProjectMember'),  
    (16, 16, 'ProjectMember'),  
    (17, 17, 'ProjectMember'),  
    (18, 18, 'ProjectMember'),  
    (19, 19, 'ProjectMember'), 
    (20, 20, 'ProjectMember'),  
    (21, 21, 'ProjectCoordinator'),  
    (22, 22, 'ProjectMember'),       
    (23, 23, 'ProjectCoordinator'),  
    (24, 24, 'ProjectMember'),       
    (25, 25, 'ProjectCoordinator'),  
    (26, 26, 'ProjectMember'),       
    (27, 27, 'ProjectCoordinator'),  
    (28, 28, 'ProjectMember'),      
    (29, 29, 'ProjectCoordinator'),  
    (30, 30, 'ProjectMember'),       
    (31, 31, 'ProjectMember'),       
    (32, 32, 'ProjectCoordinator'),  
    (33, 33, 'ProjectMember'),       
    (34, 34, 'ProjectCoordinator'),  
    (35, 35, 'ProjectMember'),       
    (36, 36, 'ProjectCoordinator'),  
    (37, 37, 'ProjectMember'),       
    (38, 38, 'ProjectCoordinator'),  
    (39, 39, 'ProjectMember'),       
    (40, 40, 'ProjectCoordinator'),  
    (1, 41, 'ProjectCoordinator'),   
    (2, 42, 'ProjectMember'),       
    (3, 43, 'ProjectCoordinator'),   
    (4, 44, 'ProjectMember'),        
    (5, 45, 'ProjectCoordinator'),  
    (6, 46, 'ProjectMember'),        
    (7, 47, 'ProjectCoordinator'),   
    (8, 48, 'ProjectMember'),        
    (9, 49, 'ProjectCoordinator'),   
    (10, 50, 'ProjectMember'),       
    (11, 51, 'ProjectCoordinator'),  
    (12, 52, 'ProjectMember'),       
    (13, 53, 'ProjectCoordinator'),  
    (14, 54, 'ProjectMember'),       
    (15, 55, 'ProjectCoordinator'),  
    (16, 56, 'ProjectMember'),       
    (17, 57, 'ProjectCoordinator'),  
    (18, 58, 'ProjectMember');       

INSERT INTO FavouriteProject (user_id, project_id)
VALUES
    (1, 1),   
    (2, 2),   
    (3, 3),   
    (4, 4),   
    (5, 5),   
    (6, 6),   
    (7, 7),  
    (8, 8),   
    (9, 9),   
    (10, 10), 
    (11, 11), 
    (12, 12), 
    (13, 13), 
    (14, 14), 
    (15, 15), 
    (16, 16),
    (17, 17), 
    (18, 18), 
    (19, 19), 
    (20, 20), 
    (21, 21),   
    (22, 22),   
    (23, 23),  
    (24, 24),  
    (25, 25),   
    (26, 26),   
    (27, 27),   
    (28, 28),   
    (29, 29),   
    (30, 30),   
    (31, 31),  
    (32, 32),   
    (33, 33),  
    (34, 34),   
    (35, 35),   
    (36, 36),  
    (37, 37),  
    (38, 38),   
    (39, 39),   
    (40, 40);  

INSERT INTO InviteNotification (created_at, user_id)
VALUES
    (NOW() - INTERVAL '1 day', 1),   
    (NOW() - INTERVAL '2 days', 2),  
    (NOW() - INTERVAL '3 days', 3),  
    (NOW() - INTERVAL '4 days', 4),  
    (NOW() - INTERVAL '5 days', 5),  
    (NOW() - INTERVAL '6 days', 6),  
    (NOW() - INTERVAL '7 days', 7),  
    (NOW() - INTERVAL '8 days', 8),  
    (NOW() - INTERVAL '9 days', 9),  
    (NOW() - INTERVAL '10 days', 10),  
    (NOW() - INTERVAL '11 days', 11), 
    (NOW() - INTERVAL '12 days', 12),  
    (NOW() - INTERVAL '13 days', 13),  
    (NOW() - INTERVAL '14 days', 14),  
    (NOW() - INTERVAL '15 days', 15),  
    (NOW() - INTERVAL '16 days', 16),  
    (NOW() - INTERVAL '17 days', 17),  
    (NOW() - INTERVAL '18 days', 18),  
    (NOW() - INTERVAL '19 days', 19),  
    (NOW() - INTERVAL '20 days', 20),  
    (NOW() - INTERVAL '21 days', 21),  
    (NOW() - INTERVAL '22 days', 22),  
    (NOW() - INTERVAL '23 days', 23),  
    (NOW() - INTERVAL '24 days', 24), 
    (NOW() - INTERVAL '25 days', 25),  
    (NOW() - INTERVAL '26 days', 26),  
    (NOW() - INTERVAL '27 days', 27),  
    (NOW() - INTERVAL '28 days', 28),  
    (NOW() - INTERVAL '29 days', 29),  
    (NOW() - INTERVAL '30 days', 30),  
    (NOW() - INTERVAL '31 days', 31),  
    (NOW() - INTERVAL '32 days', 32),  
    (NOW() - INTERVAL '33 days', 33),  
    (NOW() - INTERVAL '34 days', 34),  
    (NOW() - INTERVAL '35 days', 35),  
    (NOW() - INTERVAL '36 days', 36),  
    (NOW() - INTERVAL '37 days', 37),  
    (NOW() - INTERVAL '38 days', 38),  
    (NOW() - INTERVAL '39 days', 39),  
    (NOW() - INTERVAL '40 days', 40),  
    (NOW() - INTERVAL '41 days', 41),  
    (NOW() - INTERVAL '42 days', 42),  
    (NOW() - INTERVAL '43 days', 43);  

INSERT INTO RoleChangeNotification (created_at, updated_user, updated_project, updated_role)
VALUES
    (NOW() - INTERVAL '1 day', 1, 1, 'ProjectCoordinator'),
    (NOW() - INTERVAL '2 days', 2, 2, 'ProjectMember'),
    (NOW() - INTERVAL '3 days', 3, 3, 'ProjectCoordinator'),
    (NOW() - INTERVAL '4 days', 4, 4, 'ProjectMember'),
    (NOW() - INTERVAL '5 days', 5, 5, 'ProjectCoordinator'),
    (NOW() - INTERVAL '6 days', 6, 6, 'ProjectMember'),
    (NOW() - INTERVAL '7 days', 7, 7, 'ProjectCoordinator'),
    (NOW() - INTERVAL '8 days', 8, 8, 'ProjectMember'),
    (NOW() - INTERVAL '9 days', 9, 9, 'ProjectCoordinator'),
    (NOW() - INTERVAL '10 days', 10, 10, 'ProjectMember'),
    (NOW() - INTERVAL '11 days', 11, 11, 'ProjectCoordinator'),
    (NOW() - INTERVAL '12 days', 12, 12, 'ProjectMember'),
    (NOW() - INTERVAL '13 days', 13, 13, 'ProjectCoordinator'),
    (NOW() - INTERVAL '14 days', 14, 14, 'ProjectMember'),
    (NOW() - INTERVAL '15 days', 15, 15, 'ProjectCoordinator'),
    (NOW() - INTERVAL '16 days', 16, 16, 'ProjectMember'),
    (NOW() - INTERVAL '17 days', 17, 17, 'ProjectCoordinator'),
    (NOW() - INTERVAL '18 days', 18, 18, 'ProjectMember'),
    (NOW() - INTERVAL '19 days', 19, 19, 'ProjectCoordinator'),
    (NOW() - INTERVAL '20 days', 20, 20, 'ProjectMember');

INSERT INTO TaskNotification (created_at, task_id, notify_type)
VALUES
    (NOW() - INTERVAL '1 day', 1, 'DeadlineChanged'),   
    (NOW() - INTERVAL '2 days', 2, 'TaskPriorityChanged'),
    (NOW() - INTERVAL '3 days', 3, 'NewAssignment'),
    (NOW() - INTERVAL '4 days', 4, 'TaskCompleted'),
    (NOW() - INTERVAL '5 days', 5, 'TaskComment'),
    (NOW() - INTERVAL '6 days', 6, 'DeadlineChanged'),
    (NOW() - INTERVAL '7 days', 7, 'TaskPriorityChanged'),
    (NOW() - INTERVAL '8 days', 8, 'NewAssignment'),
    (NOW() - INTERVAL '9 days', 9, 'TaskCompleted'),
    (NOW() - INTERVAL '10 days', 10, 'TaskComment'),
    (NOW() - INTERVAL '11 days', 11, 'DeadlineChanged'),
    (NOW() - INTERVAL '12 days', 12, 'TaskPriorityChanged'),
    (NOW() - INTERVAL '13 days', 13, 'NewAssignment'),
    (NOW() - INTERVAL '14 days', 14, 'TaskCompleted'),
    (NOW() - INTERVAL '15 days', 15, 'TaskComment'),
    (NOW() - INTERVAL '16 days', 16, 'DeadlineChanged'),
    (NOW() - INTERVAL '17 days', 17, 'TaskPriorityChanged'),
    (NOW() - INTERVAL '18 days', 18, 'NewAssignment'),
    (NOW() - INTERVAL '19 days', 19, 'TaskCompleted'),
    (NOW() - INTERVAL '20 days', 20, 'TaskComment'),
    (NOW() - INTERVAL '21 days', 21, 'DeadlineChanged'),
    (NOW() - INTERVAL '22 days', 22, 'TaskPriorityChanged'),
    (NOW() - INTERVAL '23 days', 23, 'NewAssignment'),
    (NOW() - INTERVAL '24 days', 24, 'TaskCompleted'),
    (NOW() - INTERVAL '25 days', 25, 'TaskComment'),
    (NOW() - INTERVAL '26 days', 26, 'DeadlineChanged'),
    (NOW() - INTERVAL '27 days', 27, 'TaskPriorityChanged'),
    (NOW() - INTERVAL '28 days', 28, 'NewAssignment'), 
    (NOW() - INTERVAL '29 days', 29, 'TaskCompleted'),
    (NOW() - INTERVAL '30 days', 30, 'TaskComment'),
    (NOW() - INTERVAL '31 days', 31, 'DeadlineChanged'),
    (NOW() - INTERVAL '32 days', 32, 'TaskPriorityChanged'), 
    (NOW() - INTERVAL '33 days', 33, 'NewAssignment'), 
    (NOW() - INTERVAL '34 days', 34, 'TaskCompleted'),  
    (NOW() - INTERVAL '35 days', 35, 'TaskComment'), 
    (NOW() - INTERVAL '36 days', 36, 'DeadlineChanged'), 
    (NOW() - INTERVAL '37 days', 37, 'TaskPriorityChanged'),  
    (NOW() - INTERVAL '38 days', 38, 'NewAssignment'),  
    (NOW() - INTERVAL '39 days', 39, 'TaskCompleted'),  
    (NOW() - INTERVAL '40 days', 40, 'TaskComment'), 
    (NOW() - INTERVAL '41 days', 41, 'DeadlineChanged'), 
    (NOW() - INTERVAL '42 days', 42, 'TaskPriorityChanged'), 
    (NOW() - INTERVAL '43 days', 43, 'NewAssignment'), 
    (NOW() - INTERVAL '44 days', 44, 'TaskCompleted'),  
    (NOW() - INTERVAL '45 days', 45, 'TaskComment'), 
    (NOW() - INTERVAL '46 days', 46, 'DeadlineChanged'),  
    (NOW() - INTERVAL '47 days', 47, 'TaskPriorityChanged'),  
    (NOW() - INTERVAL '48 days', 48, 'NewAssignment'), 
    (NOW() - INTERVAL '49 days', 49, 'TaskCompleted'),  
    (NOW() - INTERVAL '50 days', 50, 'TaskComment');  

INSERT INTO Image (image_path, user_id)
VALUES
    ('user_1_image.jpg', 1),    
    ('user_2_image.jpg', 2),    
    ('user_3_image.jpg', 3),    
    ('user_4_image.jpg', 4),    
    ('user_5_image.jpg', 5),   
    ('user_6_image.jpg', 6),    
    ('user_7_image.jpg', 7),   
    ('user_8_image.jpg', 8),    
    ('user_9_image.jpg', 9),   
    ('user_10_image.jpg', 10),  
    ('user_11_image.jpg', 11), 
    ('user_12_image.jpg', 12),  
    ('user_13_image.jpg', 13), 
    ('user_14_image.jpg', 14), 
    ('user_15_image.jpg', 15),  
    ('user_16_image.jpg', 16),  
    ('user_17_image.jpg', 17),  
    ('user_18_image.jpg', 18),  
    ('user_19_image.jpg', 19),  
    ('user_20_image.jpg', 20),  
    ('user_21_image.jpg', 21), 
    ('user_22_image.jpg', 22),  
    ('user_23_image.jpg', 23),  
    ('user_24_image.jpg', 24),  
    ('user_25_image.jpg', 25),  
    ('user_26_image.jpg', 26), 
    ('user_27_image.jpg', 27),  
    ('user_28_image.jpg', 28), 
    ('user_29_image.jpg', 29),  
    ('user_30_image.jpg', 30),  
    ('user_31_image.jpg', 31),  
    ('user_32_image.jpg', 32);  

INSERT INTO ProjectTaskStatus (task_status_id, project_id)
VALUES
    (1, 1),   
    (2, 2),   
    (3, 3),   
    (4, 4),  
    (5, 5),   
    (6, 6),   
    (7, 7),   
    (8, 8),   
    (9, 9),   
    (10, 10), 
    (1, 11),  
    (2, 12),  
    (3, 13),  
    (4, 14),  
    (5, 15),  
    (6, 16),  
    (7, 17),  
    (8, 18),  
    (9, 19), 
    (10, 20); 